notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com


install:
    - sudo apt-get -y update
    - sudo apt-get -y --force-yes install python3 python-pip
    - sudo pip install python-libsbml
    - sudo pip install pymoose --pre --upgrade

script:
    - # Making sure no python incompatible file is added.
    - python3 -m compileall -q .
    - python3 -c 'import moose'
    - python3 setup.py install --user 
